<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Morson</title>

    <style>
        body {
            font-family: Poppins, sans-serif;
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }

        header {
            background-color: #AF0707; /* Updated color */
            color: #fff;
            text-align: center;
            padding: 50px 20px; /* Further reduced top and bottom padding */
            border-bottom: 10px solid #000;
            display: flex;
            align-items: flex-start;
            justify-content: flex-start;
        }

        h1 {
            font-size: 64px;
            margin-top: 10px;
            flex: 1;
            text-align: center;
            align-items: center; /* Center the text vertically */
            justify-content: center; /* Center the text horizontally */
            display: flex; /* Added to enable align-items and justify-content */
        }

        header img {
            max-height: 65px;
            margin-right: 10px; /* Reduced margin-right to move the image more to the left */
        }

        section {
            display: flex;
            justify-content: space-around;
            align-items: center;
            padding: 20px;
            flex-direction: row;
        }

        .data-section {
            flex: 1;
            text-align: center;
            padding: 20px;
            height: 630px;
            position: relative;
            border-right: 4px solid #000; /* Add a black right border */
        }

        .data-section:last-child {
            border-right: 0; /* Remove border from the last data section */
        }

        footer {
            background-color: #00008b;
            color: #fff;
            text-align: center;
            padding: -1px;
            margin-top: auto;
            position: relative;
        }

        .disclaimer-section {
            position: fixed;
            bottom: 60px;
            right: 10px;
            background-color: #fff; /* Add background color as needed */
            padding: 10px;
            border: 1px solid #000; /* Add border as needed */
            border-radius: 5px; /* Add border-radius for rounded corners */
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* Add box shadow for a subtle effect */
        }
    </style>
</head>
<body>

<header>
    <img src="/Views/Images/morson.png" alt="">
    <h1 style='position:relative; top:60px; left:-130px; font-size: 7em'>Business Development Updates</h1>


</header>

<section>
    <div class="data-section">
        <h2 style="font-size: 4em">Number of live bids</h2>
        <p style="font-size: 4em"><?php /** @var $view */
            echo $view->departmentDataSet['business_development']['live_bids']; ?>
        </p>
    </div>

    <div class="data-section">
        <h2 style="font-size: 4em">Total Bids</h2>
        <p style="font-size: 4em"><?php echo '£' . number_format($view->departmentDataSet['business_development']['value_live_bids']); ?></p>
    </div>

    <div class="data-section">
        <h2 style="font-size: 4em">Number of current leads</h2>
        <p style="font-size: 4em"><?php echo $view->departmentDataSet['business_development']['current_leads']; ?></p>
    </div>
</section>

<footer>
    <p>sample text</p>
</footer>

<div class="disclaimer-section">
    <p>DISCLAIMER: [HackCamp Project]</p>
</div>


</body>
</html>
<script>
    setTimeout(function(){
        window.location.reload(1);
    }, 30000);
</script>
