<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Morson</title>
    <style>
        body {
            font-family: Poppins, sans-serif;
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }

        header {
            background-color: #279989;
            color: #fff;
            text-align: center;
            padding: 50px 20px;
            border-bottom: 10px solid #000;
            display: flex;
            align-items: flex-start;
            justify-content: flex-start;
        }

        h1 {
            font-size: 64px;
            margin-top: 10px;
            flex: 1;
            text-align: center;
            align-items: center;
            justify-content: center;
            display: flex;
            position: relative;
            top: 60px;
            left: -130px;
        }

        header img {
            max-height: 65px;
            margin-right: 10px;
        }

        section {
            display: flex;
            justify-content: space-around;
            align-items: center;
            padding: 20px;
            flex-direction: row;
        }

        .data-section {
            flex: 1;
            text-align: center;
            padding: 20px;
            height: 580px;
            position: relative;
            border-right: 4px solid #000; /* Add a black right border */
        }

        .data-section:last-child {
            border-right: 0; /* Remove border from the last data section */
        }

        footer {
            background-color: #00008b;
            color: #fff;
            text-align: center;
            padding: -1px;
            margin-top: auto;
            position: relative;
        }
    </style>
</head>
<body>

<header>
    <img src="/Views/Images/morson.png" alt="">
    <h1 style='position:relative; top:60px; left:-130px'>Commerical and Accounts</h1>
</header>

<section>
    <div class="data-section">
        <h2>What day is Payday?</h2>
        <p>Payday is: <?php /** @var $view */
            echo $view->departmentDataSet['commercial_and_accounts']['payday'];?></p>
    </div>

    <div class="data-section">
        <h2>Payroll Bulletins</h2>
        <p><?php echo $view->departmentDataSet['commercial_and_accounts']['payroll_bulletin'] ?></p>
    </div>

    <div class="data-section">
        <h2>Best Performing Projects</h2>
        <p><?php echo $view->departmentDataSet['commercial_and_accounts']['best_performing_projects'] ?></p>
    </div>
</section>

<footer>
    <p>sample text</p>
</footer>

<!-- Add more sections or content as needed -->

</body>
</html>
<script>
    setTimeout(function(){
        window.location.reload(1);
    }, 30000);
</script>
