<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/Views/mystyles.css">
    <title>Morson</title>
</head>
<body>

<header class="commercial">
    <img src="/Views/Images/morson-white.png" alt="">
    <h1 style='position:relative; top:60px; left:-130px; font-size: 7em'>Commerical and Accounts</h1>
</header>

<div class="container">
    <div class="row">
        <div class="col-md data-section">
            <h2 style="font-size: 4em">When day is Payday?</h2>
            <p id="payday" style="font-size: 3em"></p>
        </div>

        <div class="col-md data-section">
            <h2 style="font-size: 4em">Payroll Bulletins</h2>
            <p id="payrollBulletin" style="font-size: 3em"></p>
        </div>

        <div class="col-md data-section">
            <h2 style="font-size: 4em">Best Performing Projects</h2>
            <p id="bestPerformingProjects" style="font-size: 4em"></p>
        </div>
    </div>
</div>



<div class="disclaimer-section">
    <p style="font-size: 20px; color:red">DISCLAIMER: [This is a HackCamp Project, and does not reflect the views of Morson Projects, or Morson Group.]</p>
</div>

<!-- Add more sections or content as needed -->

</body>
</html>


