<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Morson</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/Views/mystyles.css"></head>
<body>

<header class="itSystems">
    <img src="/Views/Images/morson-white.png" alt="">
    <h1 style='position:relative; top:60px; left:-130px; font-size: 7em'>IT and Systems</h1>
</header>

<div class="container">
    <div class="row">
        <div class="col-md data-section padded" id="scheduledOutagesContainer">
            <h2 style="font-size: 4em">Scheduled Outages</h2>
            <p id="scheduledOutages" style="font-size: 4em"></p>
        </div>

        <div class="col-md data-section padded" id="softwareStatus">
            <h2 style="font-size: 4em">Build Status - Software</h2>
            <p id="softwareStatus" style="font-size: 4em"></p>
        </div>

        <div class="col-md data-section padded" id="systemStatus">
            <h2 style="font-size: 3em">System Status</h2>
            <p id="systemStatus" style="font-size: 4em"></p>
        </div>
    </div>
</div>



<div class="disclaimer-section">
    <p style="font-size: 20px; color:red">DISCLAIMER: [This is a HackCamp Project, and does not reflect the views of Morson Projects, or Morson Group.]</p>
</div>

<!-- Add more sections or content as needed -->

</body>
</html>







