<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link rel="stylesheet" href="Views/style.css">
    <title>Morson Login</title>

</head>

<body>

<div class="container" id="container">

    <div class="form-container sign-in">

        <form action="../login.php" method="post">
            <h1><u>Sign In</u></h1>
            <input type="email" name="email" placeholder="Email">
            <input type="password" name="password" placeholder="Password">
            <input type="submit" name="submit" value="Sign In">
        </form>

    </div>


    <div class="toggle-container">

        <div class="toggle">

            <div class="toggle-panel toggle-right">

                <h1>We are the Morson Group: Placing People First</h1>
                <p>We’re creating a better, more innovative world – inspiring, supporting, reskilling and nurturing the
                    talent of today, tomorrow and the future.</p>

            </div>

        </div>


    </div>

</div>

</body>

</html>