on:
  push:
    branches:
    - feat/development
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: rsync deploy
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete
        path: src/
        remote_path: ~/public_html/
        remote_host: ${{ secrets.REMOTE_HOST }}
        remote_user: ${{ secrets.REMOTE_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
